CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory"
(
    "MigrationId"    character varying(150) NOT NULL,
    "ProductVersion" character varying(32)  NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO
$EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240325200642_Initial') THEN
            CREATE TABLE "RegistrosAuditoria"
            (
                "Id"           integer GENERATED BY DEFAULT AS IDENTITY,
                "Usuario"      text                        NULL,
                "Entidade"     text                        NOT NULL,
                "Acao"         text                        NOT NULL,
                "Timestamp"    timestamp                   NOT NULL,
                "Alteracoes"   text                        NOT NULL,
                "CriadoEm"     timestamp without time zone NOT NULL,
                "AtualizadoEm" timestamp without time zone NOT NULL,
                CONSTRAINT "PK_RegistrosAuditoria" PRIMARY KEY ("Id")
            );
        END IF;
    END
$EF$;

DO
$EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240325200642_Initial') THEN
            CREATE TABLE "Usuarios"
            (
                "Id"           integer GENERATED BY DEFAULT AS IDENTITY,
                "Nome"         text      NOT NULL,
                "Email"        text      NULL,
                "Telefone"     text      NULL,
                "Documento"    text      NULL,
                "Ativo"        boolean   NOT NULL,
                "CriadoEm"     timestamp NOT NULL,
                "AtualizadoEm" timestamp NOT NULL,
                CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
            );
        END IF;
    END
$EF$;

DO
$EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240325200642_Initial') THEN
            CREATE TABLE "Endereco"
            (
                "Id"           integer GENERATED BY DEFAULT AS IDENTITY,
                "UsuarioId"    integer   NOT NULL,
                "Logradouro"   text      NOT NULL,
                "Numero"       text      NOT NULL,
                "Complemento"  text      NULL,
                "Cep"          text      NOT NULL,
                "Bairro"       text      NOT NULL,
                "Cidade"       text      NOT NULL,
                "Uf"           text      NOT NULL,
                "CriadoEm"     timestamp NOT NULL,
                "AtualizadoEm" timestamp NOT NULL,
                CONSTRAINT "PK_Endereco" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_Endereco_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
            );
        END IF;
    END
$EF$;

DO
$EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240325200642_Initial') THEN
            CREATE UNIQUE INDEX "IX_Endereco_UsuarioId" ON "Endereco" ("UsuarioId");
        END IF;
    END
$EF$;

DO
$EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240325200642_Initial') THEN
            INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
            VALUES ('20240325200642_Initial', '7.0.13');
        END IF;
    END
$EF$;
COMMIT;

